// Kanji characters and their meanings/readings organized by grade.
// Derived from Wikipedia contributors, "Kyōiku kanji", Wikipedia, The Free Encyclopedia.
// See NOTICE and CONTENT-LICENSE.md for attribution and licensing details.
(() => {
const kanjiDataByGrade = [
    // Grade 1 (80 kanji)
    {
        grade: 1,
        kanji: [
            { char: "一", meaning: "one", on: ["いち", "いつ"], kun: ["ひと", "ひとつ"] },
            { char: "二", meaning: "two", on: ["に", "じ"], kun: ["ふた", "ふたつ"] },
            { char: "三", meaning: "three", on: ["さん"], kun: ["み", "みつ", "みっつ"] },
            { char: "四", meaning: "four", on: ["し"], kun: ["よ", "よつ", "よっつ", "よん"] },
            { char: "五", meaning: "five", on: ["ご"], kun: ["いつ", "いつつ"] },
            { char: "六", meaning: "six", on: ["ろく"], kun: ["む", "むつ", "むっつ", "むい"] },
            { char: "七", meaning: "seven", on: ["しち"], kun: ["なな", "ななつ", "なの"] },
            { char: "八", meaning: "eight", on: ["はち"], kun: ["や", "やつ", "やっつ", "よう"] },
            { char: "九", meaning: "nine", on: ["く", "きゅう"], kun: ["ここの", "ここのつ"] },
            { char: "十", meaning: "ten", on: ["じゅう", "じっ"], kun: ["とお", "と"] },
            { char: "百", meaning: "hundred", on: ["ひゃく"], kun: ["もも"] },
            { char: "千", meaning: "thousand", on: ["せん"], kun: ["ち"] },
            { char: "上", meaning: "top", on: ["じょう"], kun: ["うえ", "あげる", "あがる", "のぼる", "かみ", "うわ"] },
            { char: "下", meaning: "below", on: ["か", "げ"], kun: ["した", "しも", "さげる", "さがる", "くだる", "くだす", "くださる", "おろす", "おりる"] },
            { char: "左", meaning: "left", on: ["さ"], kun: ["ひだり"] },
            { char: "右", meaning: "right", on: ["う", "ゆう"], kun: ["みぎ"] },
            { char: "中", meaning: "middle", on: ["ちゅう", "じゅう"], kun: ["なか"] },
            { char: "大", meaning: "large", on: ["だい", "たい"], kun: ["おお", "おおきい", "おおいに"] },
            { char: "小", meaning: "small", on: ["しょう"], kun: ["ちいさい", "こ", "お"] },
            { char: "月", meaning: "moon", on: ["げつ", "がつ"], kun: ["つき"] },
            { char: "日", meaning: "day", on: ["にち", "じつ"], kun: ["ひ", "か"] },
            { char: "年", meaning: "year", on: ["ねん"], kun: ["とし"] },
            { char: "早", meaning: "early", on: ["そう"], kun: ["はやい", "はやめる", "はやまる"] },
            { char: "木", meaning: "tree", on: ["もく", "ぼく"], kun: ["き", "こ"] },
            { char: "林", meaning: "woods", on: ["りん"], kun: ["はやし"] },
            { char: "山", meaning: "mountain", on: ["さん"], kun: ["やま"] },
            { char: "川", meaning: "river", on: ["せん"], kun: ["かわ"] },
            { char: "土", meaning: "soil", on: ["ど", "と"], kun: ["つち"] },
            { char: "空", meaning: "sky", on: ["くう"], kun: ["そら", "あく", "あける", "から"] },
            { char: "田", meaning: "rice field", on: ["でん"], kun: ["た"] },
            { char: "天", meaning: "heaven", on: ["てん"], kun: ["あめ", "あま"] },
            { char: "生", meaning: "life", on: ["せい", "しょう"], kun: ["いきる", "うむ", "うまれる", "なま"] },
            { char: "花", meaning: "flower", on: ["か"], kun: ["はな"] },
            { char: "草", meaning: "grass", on: ["そう"], kun: ["くさ"] },
            { char: "虫", meaning: "insect", on: ["ちゅう"], kun: ["むし"] },
            { char: "犬", meaning: "dog", on: ["けん"], kun: ["いぬ"] },
            { char: "人", meaning: "person", on: ["じん", "にん"], kun: ["ひと"] },
            { char: "名", meaning: "name", on: ["めい", "みょう"], kun: ["な"] },
            { char: "女", meaning: "woman", on: ["じょ", "にょ"], kun: ["おんな", "め"] },
            { char: "男", meaning: "man", on: ["だん", "なん"], kun: ["おとこ"] },
            { char: "子", meaning: "child", on: ["し", "す"], kun: ["こ"] },
            { char: "目", meaning: "eye", on: ["もく"], kun: ["め"] },
            { char: "耳", meaning: "ear", on: ["じ"], kun: ["みみ"] },
            { char: "口", meaning: "mouth", on: ["こう"], kun: ["くち"] },
            { char: "手", meaning: "hand", on: ["しゅ"], kun: ["て"] },
            { char: "足", meaning: "foot", on: ["そく"], kun: ["あし"] },
            { char: "見", meaning: "see", on: ["けん"], kun: ["みる"] },
            { char: "音", meaning: "sound", on: ["おん"], kun: ["おと", "ね"] },
            { char: "力", meaning: "power", on: ["りき", "りょく"], kun: ["ちから"] },
            { char: "気", meaning: "spirit", on: ["き", "け"], kun: ["いき"] },
            { char: "円", meaning: "circle", on: ["えん"], kun: ["まる"] },
            { char: "入", meaning: "enter", on: ["にゅう"], kun: ["はいる", "いれる"] },
            { char: "出", meaning: "exit", on: ["しゅつ"], kun: ["でる", "だす"] },
            { char: "立", meaning: "stand", on: ["りつ"], kun: ["たつ"] },
            { char: "休", meaning: "rest", on: ["きゅう"], kun: ["やすむ"] },
            { char: "先", meaning: "previous", on: ["せん"], kun: ["さき"] },
            { char: "夕", meaning: "evening", on: ["せき"], kun: ["ゆう"] },
            { char: "本", meaning: "book", on: ["ほん"], kun: ["もと"] },
            { char: "文", meaning: "sentence", on: ["ぶん", "もん"], kun: ["ふみ"] },
            { char: "字", meaning: "character", on: ["じ"], kun: ["あざ"] },
            { char: "学", meaning: "study", on: ["がく"], kun: ["まなぶ"] },
            { char: "校", meaning: "school", on: ["こう"], kun: [] },
            { char: "村", meaning: "village", on: ["そん"], kun: ["むら"] },
            { char: "町", meaning: "town", on: ["ちょう"], kun: ["まち"] },
            { char: "森", meaning: "forest", on: ["しん"], kun: ["もり"] },
            { char: "正", meaning: "correct", on: ["せい", "しょう"], kun: ["ただしい", "ただす", "まさ"] },
            { char: "水", meaning: "water", on: ["すい"], kun: ["みず"] },
            { char: "火", meaning: "fire", on: ["か"], kun: ["ひ"] },
            { char: "玉", meaning: "jewel", on: ["ぎょく"], kun: ["たま"] },
            { char: "王", meaning: "king", on: ["おう"], kun: [] },
            { char: "石", meaning: "stone", on: ["せき"], kun: ["いし"] },
            { char: "竹", meaning: "bamboo", on: ["ちく"], kun: ["たけ"] },
            { char: "糸", meaning: "thread", on: ["し"], kun: ["いと"] },
            { char: "貝", meaning: "shellfish", on: [], kun: ["かい"] },
            { char: "車", meaning: "car", on: ["しゃ"], kun: ["くるま"] },
            { char: "金", meaning: "gold", on: ["きん"], kun: ["かね"] },
            { char: "雨", meaning: "rain", on: ["う"], kun: ["あめ", "あま"] },
            { char: "赤", meaning: "red", on: ["せき"], kun: ["あか"] },
            { char: "青", meaning: "blue", on: ["せい", "しょう"], kun: ["あお"] },
            { char: "白", meaning: "white", on: ["はく"], kun: ["しろ", "しら"] }
        ]
    },

    // Grade 2 (160 kanji)
    {
        grade: 2,
        kanji: [
            { char: "数", meaning: "number", on: ["すう"], kun: ["かず"] },
            { char: "多", meaning: "many", on: ["た"], kun: ["おおい"] },
            { char: "少", meaning: "few", on: ["しょう"], kun: ["すくない", "すこし"] },
            { char: "万", meaning: "ten thousand", on: ["まん", "ばん"], kun: ["よろず"] },
            { char: "半", meaning: "half", on: ["はん"], kun: ["なかば"] },
            { char: "形", meaning: "shape", on: ["けい", "ぎょう"], kun: ["かたち"] },
            { char: "太", meaning: "thick", on: ["た"], kun: ["ふとい"] },
            { char: "細", meaning: "thin", on: ["さい"], kun: ["ほそい"] },
            { char: "広", meaning: "wide", on: ["こう"], kun: ["ひろい"] },
            { char: "長", meaning: "long", on: ["ちょう"], kun: ["ながい"] },
            { char: "点", meaning: "point", on: ["てん"], kun: ["ぼち"] },
            { char: "丸", meaning: "circle", on: ["がん"], kun: ["まる"] },
            { char: "交", meaning: "mix", on: ["こう"], kun: ["まじわる"] },
            { char: "光", meaning: "light", on: ["こう"], kun: ["ひかり"] },
            { char: "角", meaning: "angle", on: ["かく"], kun: ["かど", "つの"] },
            { char: "計", meaning: "measure", on: ["けい"], kun: ["はかる"] },
            { char: "直", meaning: "straight", on: ["ちょく", "じき"], kun: ["なおす", "ただちに"] },
            { char: "線", meaning: "line", on: ["せん"], kun: [] },
            { char: "矢", meaning: "arrow", on: ["し"], kun: ["や"] },
            { char: "弱", meaning: "weak", on: ["じゃく"], kun: ["よわい"] },
            { char: "羽", meaning: "feather", on: ["う"], kun: ["は", "わ"] },
            { char: "雲", meaning: "cloud", on: ["うん"], kun: ["くも"] },
            { char: "園", meaning: "garden", on: ["えん"], kun: ["その"] },
            { char: "遠", meaning: "distant", on: ["えん"], kun: ["とおい"] },
            { char: "何", meaning: "what", on: ["か"], kun: ["なに", "なん"] },
            { char: "夏", meaning: "summer", on: ["か"], kun: ["なつ"] },
            { char: "家", meaning: "house", on: ["か"], kun: ["いえ", "や"] },
            { char: "歌", meaning: "song", on: ["か"], kun: ["うた", "うたう"] },
            { char: "回", meaning: "turn", on: ["かい"], kun: ["まわる", "まわす"] },
            { char: "会", meaning: "meet", on: ["かい"], kun: ["あう"] },
            { char: "海", meaning: "sea", on: ["かい"], kun: ["うみ"] },
            { char: "絵", meaning: "picture", on: ["かい"], kun: ["え"] },
            { char: "外", meaning: "outside", on: ["がい"], kun: ["そと", "ほか", "はずれる", "はずす"] },
            { char: "楽", meaning: "music", on: ["がく", "らく"], kun: ["たのしい", "たのしむ"] },
            { char: "活", meaning: "lively", on: ["かつ"], kun: [] },
            { char: "間", meaning: "interval", on: ["かん", "けん"], kun: ["あいだ", "ま"] },
            { char: "丸", meaning: "round", on: ["がん"], kun: ["まるい"] },
            { char: "岩", meaning: "rock", on: ["がん"], kun: ["いわ"] },
            { char: "顔", meaning: "face", on: ["がん"], kun: ["かお"] },
            { char: "汽", meaning: "steam", on: ["き"], kun: [] },
            { char: "記", meaning: "write", on: ["き"], kun: ["しるす"] },
            { char: "帰", meaning: "return", on: ["き"], kun: ["かえる"] },
            { char: "客", meaning: "guest", on: ["きゃく"], kun: [] },
            { char: "牛", meaning: "cow", on: ["ぎゅう"], kun: ["うし"] },
            { char: "魚", meaning: "fish", on: ["ぎょ"], kun: ["うお", "さかな"] },
            { char: "京", meaning: "capital", on: ["きょう"], kun: [] },
            { char: "強", meaning: "strong", on: ["きょう", "ごう"], kun: ["つよい", "しいる"] },
            { char: "教", meaning: "teach", on: ["きょう"], kun: ["おしえる"] },
            { char: "近", meaning: "near", on: ["きん"], kun: ["ちかい"] },
            { char: "兄", meaning: "older brother", on: ["けい", "きょう"], kun: ["あに"] },
            { char: "形", meaning: "shape", on: ["けい", "ぎょう"], kun: ["かたち"] },
            { char: "計", meaning: "measure", on: ["けい"], kun: ["はかる"] },
            { char: "元", meaning: "origin", on: ["げん", "がん"], kun: ["もと"] },
            { char: "言", meaning: "say", on: ["げん", "ごん"], kun: ["いう", "こと"] },
            { char: "原", meaning: "meadow", on: ["げん"], kun: ["はら"] },
            { char: "戸", meaning: "door", on: ["こ"], kun: ["と"] },
            { char: "古", meaning: "old", on: ["こ"], kun: ["ふるい"] },
            { char: "午", meaning: "noon", on: ["ご"], kun: [] },
            { char: "後", meaning: "after", on: ["ご", "こう"], kun: ["うしろ", "あと"] },
            { char: "語", meaning: "language", on: ["ご"], kun: ["かたる"] },
            { char: "工", meaning: "craft", on: ["こう", "く"], kun: [] },
            { char: "広", meaning: "wide", on: ["こう"], kun: ["ひろい"] },
            { char: "交", meaning: "mix", on: ["こう"], kun: ["まじわる"] },
            { char: "光", meaning: "light", on: ["こう"], kun: ["ひかり"] },
            { char: "考", meaning: "consider", on: ["こう"], kun: ["かんがえる"] },
            { char: "行", meaning: "go", on: ["こう", "ぎょう", "あん"], kun: ["いく", "ゆく", "おこなう"] },
            { char: "高", meaning: "high", on: ["こう"], kun: ["たかい"] },
            { char: "黄", meaning: "yellow", on: ["こう", "おう"], kun: ["き"] },
            { char: "合", meaning: "fit", on: ["ごう", "がっ", "かつ"], kun: ["あう"] },
            { char: "谷", meaning: "valley", on: ["こく"], kun: ["たに"] },
            { char: "国", meaning: "country", on: ["こく"], kun: ["くに"] },
            { char: "黒", meaning: "black", on: ["こく"], kun: ["くろい"] },
            { char: "今", meaning: "now", on: ["こん", "きん"], kun: ["いま"] },
            { char: "才", meaning: "genius", on: ["さい"], kun: [] },
            { char: "細", meaning: "thin", on: ["さい"], kun: ["ほそい"] },
            { char: "作", meaning: "make", on: ["さく", "さ"], kun: ["つくる"] },
            { char: "算", meaning: "calculate", on: ["さん"], kun: [] },
            { char: "止", meaning: "stop", on: ["し"], kun: ["とまる", "とめる"] },
            { char: "市", meaning: "market", on: ["し"], kun: ["いち"] },
            { char: "矢", meaning: "arrow", on: ["し"], kun: ["や"] },
            { char: "私", meaning: "private", on: ["し"], kun: ["わたくし"] },
            { char: "思", meaning: "think", on: ["し"], kun: ["おもう"] },
            { char: "紙", meaning: "paper", on: ["し"], kun: ["かみ"] },
            { char: "寺", meaning: "temple", on: ["じ"], kun: ["てら"] },
            { char: "時", meaning: "time", on: ["じ"], kun: ["とき"] },
            { char: "室", meaning: "room", on: ["しつ"], kun: ["むろ"] },
            { char: "社", meaning: "shrine", on: ["しゃ"], kun: ["やしろ"] },
            { char: "弱", meaning: "weak", on: ["じゃく"], kun: ["よわい"] },
            { char: "首", meaning: "neck", on: ["しゅ"], kun: ["くび"] },
            { char: "秋", meaning: "autumn", on: ["しゅう"], kun: ["あき"] },
            { char: "終", meaning: "end", on: ["しゅう"], kun: ["おわる"] },
            { char: "習", meaning: "learn", on: ["しゅう"], kun: ["ならう"] },
            { char: "春", meaning: "spring", on: ["しゅん"], kun: ["はる"] },
            { char: "書", meaning: "write", on: ["しょ"], kun: ["かく"] },
            { char: "場", meaning: "location", on: ["じょう"], kun: ["ば"] },
            { char: "色", meaning: "color", on: ["しょく", "しき"], kun: ["いろ"] },
            { char: "食", meaning: "eat", on: ["しょく"], kun: ["たべる"] },
            { char: "心", meaning: "heart", on: ["しん"], kun: ["こころ"] },
            { char: "新", meaning: "new", on: ["しん"], kun: ["あたらしい"] },
            { char: "親", meaning: "parent", on: ["しん"], kun: ["おや", "したしい"] },
            { char: "図", meaning: "drawing", on: ["ず", "と"], kun: ["はかる"] },
            { char: "数", meaning: "number", on: ["すう"], kun: ["かず"] },
            { char: "西", meaning: "west", on: ["せい", "さい"], kun: ["にし"] },
            { char: "声", meaning: "voice", on: ["せい"], kun: ["こえ"] },
            { char: "星", meaning: "star", on: ["せい"], kun: ["ほし"] },
            { char: "晴", meaning: "clear", on: ["せい"], kun: ["はれる"] },
            { char: "切", meaning: "cut", on: ["せつ"], kun: ["きる"] },
            { char: "雪", meaning: "snow", on: ["せつ"], kun: ["ゆき"] },
            { char: "船", meaning: "ship", on: ["せん"], kun: ["ふね"] },
            { char: "線", meaning: "line", on: ["せん"], kun: [] },
            { char: "前", meaning: "before", on: ["ぜん"], kun: ["まえ"] },
            { char: "早", meaning: "early", on: ["そう"], kun: ["はやい"] },
            { char: "走", meaning: "run", on: ["そう"], kun: ["はしる"] },
            { char: "多", meaning: "many", on: ["た"], kun: ["おおい"] },
            { char: "太", meaning: "thick", on: ["た"], kun: ["ふとい"] },
            { char: "体", meaning: "body", on: ["たい"], kun: ["からだ"] },
            { char: "台", meaning: "pedestal", on: ["たい"], kun: ["うてな"] },
            { char: "地", meaning: "earth", on: ["ち"], kun: [] },
            { char: "知", meaning: "know", on: ["ち"], kun: ["しる"] },
            { char: "池", meaning: "pond", on: ["ち"], kun: ["いけ"] },
            { char: "茶", meaning: "tea", on: ["ちゃ", "さ"], kun: [] },
            { char: "昼", meaning: "daytime", on: ["ちゅう"], kun: ["ひる"] },
            { char: "朝", meaning: "morning", on: ["ちょう"], kun: ["あさ"] },
            { char: "長", meaning: "long", on: ["ちょう"], kun: ["ながい"] },
            { char: "鳥", meaning: "bird", on: ["ちょう"], kun: ["とり"] },
            { char: "弟", meaning: "younger brother", on: ["てい", "だい"], kun: ["おとうと"] },
            { char: "点", meaning: "point", on: ["てん"], kun: ["ぼち"] },
            { char: "店", meaning: "shop", on: ["てん"], kun: ["みせ"] },
            { char: "田", meaning: "rice field", on: ["でん"], kun: ["た"] },
            { char: "電", meaning: "electricity", on: ["でん"], kun: [] },
            { char: "刀", meaning: "sword", on: ["とう"], kun: ["かたな"] },
            { char: "冬", meaning: "winter", on: ["とう"], kun: ["ふゆ"] },
            { char: "東", meaning: "east", on: ["とう"], kun: ["ひがし"] },
            { char: "答", meaning: "answer", on: ["とう"], kun: ["こたえる"] },
            { char: "頭", meaning: "head", on: ["とう"], kun: ["あたま"] },
            { char: "同", meaning: "same", on: ["どう"], kun: ["おなじ"] },
            { char: "道", meaning: "road", on: ["どう"], kun: ["みち"] },
            { char: "読", meaning: "read", on: ["どく", "とく"], kun: ["よむ"] },
            { char: "内", meaning: "inside", on: ["ない"], kun: ["うち"] },
            { char: "南", meaning: "south", on: ["なん"], kun: ["みなみ"] },
            { char: "二", meaning: "two", on: ["に", "じ"], kun: ["ふた"] },
            { char: "肉", meaning: "meat", on: ["にく"], kun: [] },
            { char: "日", meaning: "day", on: ["にち", "じつ"], kun: ["ひ", "か"] },
            { char: "入", meaning: "enter", on: ["にゅう"], kun: ["いる"] },
            { char: "年", meaning: "year", on: ["ねん"], kun: ["とし"] },
            { char: "白", meaning: "white", on: ["はく"], kun: ["しろ"] },
            { char: "八", meaning: "eight", on: ["はち"], kun: ["やっつ"] },
            { char: "半", meaning: "half", on: ["はん"], kun: ["なかば"] },
            { char: "飯", meaning: "meal", on: ["はん"], kun: ["めし"] },
            { char: "父", meaning: "father", on: ["ふ"], kun: ["ちち"] },
            { char: "分", meaning: "minute", on: ["ぶん", "ふん", "ぶ"], kun: ["わける"] },
            { char: "聞", meaning: "hear", on: ["ぶん"], kun: ["きく"] },
            { char: "米", meaning: "rice", on: ["べい", "まい"], kun: ["こめ"] },
            { char: "歩", meaning: "walk", on: ["ほ", "ぶ", "ふ"], kun: ["あるく"] },
            { char: "北", meaning: "north", on: ["ほく"], kun: ["きた"] },
            { char: "毎", meaning: "every", on: ["まい"], kun: ["ごと"] },
            { char: "万", meaning: "ten thousand", on: ["まん", "ばん"], kun: ["よろず"] },
            { char: "名", meaning: "name", on: ["めい", "みょう"], kun: ["な"] },
            { char: "母", meaning: "mother", on: ["ぼ"], kun: ["はは"] },
            { char: "方", meaning: "direction", on: ["ほう"], kun: ["かた"] },
            { char: "野", meaning: "field", on: ["や"], kun: ["の"] },
            { char: "友", meaning: "friend", on: ["ゆう"], kun: ["とも"] },
            { char: "曜", meaning: "weekday", on: ["よう"], kun: [] },
            { char: "来", meaning: "come", on: ["らい"], kun: ["くる"] },
            { char: "理", meaning: "reason", on: ["り"], kun: [] },
            { char: "話", meaning: "talk", on: ["わ"], kun: ["はなす"] }
        ]
    },

    // Grade 3 (200 kanji)
    {
        grade: 3,
        kanji: [
            { char: "丁", meaning: "street", on: ["ちょう"], kun: ["ひのと"] },
            { char: "世", meaning: "world", on: ["せい", "せ"], kun: ["よ"] },
            { char: "両", meaning: "both", on: ["りょう"], kun: ["てる", "ふたつ"] },
            { char: "主", meaning: "master", on: ["しゅ"], kun: ["ぬし", "おも"] },
            { char: "乗", meaning: "ride", on: ["じょう"], kun: ["のる"] },
            { char: "予", meaning: "beforehand", on: ["よ"], kun: ["あらかじめ"] },
            { char: "事", meaning: "matter", on: ["じ"], kun: ["こと"] },
            { char: "仕", meaning: "serve", on: ["し"], kun: ["つかえる"] },
            { char: "他", meaning: "other", on: ["た"], kun: ["ほか"] },
            { char: "代", meaning: "substitute", on: ["だい", "たい"], kun: ["かわる", "よ"] },
            { char: "住", meaning: "dwell", on: ["じゅう"], kun: ["すむ"] },
            { char: "使", meaning: "use", on: ["し"], kun: ["つかう"] },
            { char: "係", meaning: "person in charge", on: ["けい"], kun: ["かかり", "かかる"] },
            { char: "倍", meaning: "double", on: ["ばい"], kun: [] },
            { char: "全", meaning: "whole", on: ["ぜん"], kun: ["まったく"] },
            { char: "具", meaning: "tool", on: ["ぐ"], kun: ["そなえる"] },
            { char: "写", meaning: "copy", on: ["しゃ"], kun: ["うつす"] },
            { char: "列", meaning: "row", on: ["れつ"], kun: [] },
            { char: "助", meaning: "help", on: ["じょ"], kun: ["たすける"] },
            { char: "勉", meaning: "diligence", on: ["べん"], kun: ["つとめる"] },
            { char: "務", meaning: "task", on: ["む"], kun: ["つとめる"] },
            { char: "力", meaning: "power", on: ["りょく", "りき"], kun: ["ちから"] },
            { char: "動", meaning: "move", on: ["どう"], kun: ["うごく"] },
            { char: "勝", meaning: "win", on: ["しょう"], kun: ["かつ"] },
            { char: "化", meaning: "change", on: ["か"], kun: ["ばける"] },
            { char: "区", meaning: "ward", on: ["く"], kun: [] },
            { char: "医", meaning: "doctor", on: ["い"], kun: [] },
            { char: "去", meaning: "past", on: ["きょ", "こ"], kun: ["さる"] },
            { char: "反", meaning: "anti", on: ["はん"], kun: ["そる"] },
            { char: "打", meaning: "strike", on: ["だ"], kun: ["うつ"] },
            { char: "史", meaning: "history", on: ["し"], kun: [] },
            { char: "司", meaning: "official", on: ["し"], kun: ["つかさどる"] },
            { char: "号", meaning: "number", on: ["ごう"], kun: [] },
            { char: "央", meaning: "center", on: ["おう"], kun: [] },
            { char: "回", meaning: "turn", on: ["かい"], kun: ["まわる"] },
            { char: "因", meaning: "cause", on: ["いん"], kun: ["よる"] },
            { char: "回", meaning: "times", on: ["かい"], kun: ["まわる"] },
            { char: "士", meaning: "gentleman", on: ["し"], kun: [] },
            { char: "夕", meaning: "evening", on: ["せき"], kun: ["ゆう"] },
            { char: "多", meaning: "many", on: ["た"], kun: ["おおい"] },
            { char: "大", meaning: "large", on: ["だい"], kun: ["おおきい"] },
            { char: "天", meaning: "heaven", on: ["てん"], kun: ["あめ", "あま"] },
            { char: "太", meaning: "thick", on: ["たい", "た"], kun: ["ふとい"] },
            { char: "夫", meaning: "husband", on: ["ふ"], kun: ["おっと"] },
            { char: "失", meaning: "lose", on: ["しつ"], kun: ["うしなう"] },
            { char: "好", meaning: "like", on: ["こう"], kun: ["すき", "このむ"] },
            { char: "妹", meaning: "younger sister", on: ["まい"], kun: ["いもうと"] },
            { char: "姉", meaning: "older sister", on: ["し"], kun: ["あね"] },
            { char: "始", meaning: "begin", on: ["し"], kun: ["はじめる"] },
            { char: "字", meaning: "character", on: ["じ"], kun: ["あざ"] },
            { char: "安", meaning: "cheap", on: ["あん"], kun: ["やすい"] },
            { char: "守", meaning: "guard", on: ["しゅ"], kun: ["まもる"] },
            { char: "完", meaning: "perfect", on: ["かん"], kun: [] },
            { char: "宣", meaning: "proclaim", on: ["せん"], kun: ["のる"] },
            { char: "実", meaning: "truth", on: ["じつ"], kun: ["みのる"] },
            { char: "宮", meaning: "shrine", on: ["きゅう", "ぐう"], kun: ["みや"] },
            { char: "害", meaning: "harm", on: ["がい"], kun: [] },
            { char: "定", meaning: "establish", on: ["てい"], kun: ["さだめる"] },
            { char: "客", meaning: "guest", on: ["きゃく"], kun: [] },
            { char: "室", meaning: "room", on: ["しつ"], kun: ["むろ"] },
            { char: "対", meaning: "opposite", on: ["たい"], kun: ["つち"] },
            { char: "差", meaning: "distinction", on: ["さ"], kun: ["さす"] },
            { char: "屋", meaning: "roof", on: ["おく"], kun: ["や"] },
            { char: "岸", meaning: "beach", on: ["がん"], kun: ["きし"] },
            { char: "島", meaning: "island", on: ["とう"], kun: ["しま"] },
            { char: "川", meaning: "river", on: ["せん"], kun: ["かわ"] },
            { char: "州", meaning: "state", on: ["しゅう"], kun: ["す"] },
            { char: "帳", meaning: "notebook", on: ["ちょう"], kun: ["とばり"] },
            { char: "平", meaning: "flat", on: ["へい", "びょう"], kun: ["たいら"] },
            { char: "幸", meaning: "happiness", on: ["こう"], kun: ["さいわい"] },
            { char: "度", meaning: "degree", on: ["ど"], kun: ["たび"] },
            { char: "広", meaning: "wide", on: ["こう"], kun: ["ひろい"] },
            { char: "康", meaning: "ease", on: ["こう"], kun: [] },
            { char: "建", meaning: "build", on: ["けん"], kun: ["たてる"] },
            { char: "引", meaning: "pull", on: ["いん"], kun: ["ひく"] },
            { char: "弱", meaning: "weak", on: ["じゃく"], kun: ["よわい"] },
            { char: "強", meaning: "strong", on: ["きょう", "ごう"], kun: ["つよい"] },
            { char: "当", meaning: "hit", on: ["とう"], kun: ["あたる"] },
            { char: "形", meaning: "shape", on: ["けい"], kun: ["かたち"] },
            { char: "後", meaning: "behind", on: ["ご", "こう"], kun: ["うしろ", "あと"] },
            { char: "待", meaning: "wait", on: ["たい"], kun: ["まつ"] },
            { char: "心", meaning: "heart", on: ["しん"], kun: ["こころ"] },
            { char: "思", meaning: "think", on: ["し"], kun: ["おもう"] },
            { char: "応", meaning: "respond", on: ["おう"], kun: ["こたえる"] },
            { char: "情", meaning: "feeling", on: ["じょう"], kun: [] },
            { char: "想", meaning: "concept", on: ["そう"], kun: ["おもう"] },
            { char: "才", meaning: "genius", on: ["さい"], kun: [] },
            { char: "戸", meaning: "door", on: ["こ"], kun: ["と"] },
            { char: "教", meaning: "teach", on: ["きょう"], kun: ["おしえる"] },
            { char: "書", meaning: "write", on: ["しょ"], kun: ["かく"] },
            { char: "根", meaning: "root", on: ["こん"], kun: ["ね"] },
            { char: "格", meaning: "status", on: ["かく"], kun: [] },
            { char: "校", meaning: "school", on: ["こう"], kun: [] },
            { char: "業", meaning: "business", on: ["ぎょう"], kun: ["わざ"] },
            { char: "林", meaning: "grove", on: ["りん"], kun: ["はやし"] },
            { char: "植", meaning: "plant", on: ["しょく"], kun: ["うえる"] },
            { char: "械", meaning: "mechanism", on: ["かい"], kun: [] },
            { char: "欠", meaning: "lack", on: ["けつ"], kun: ["かける"] },
            { char: "次", meaning: "next", on: ["じ", "し"], kun: ["つぐ"] },
            { char: "止", meaning: "stop", on: ["し"], kun: ["とまる"] },
            { char: "歩", meaning: "walk", on: ["ほ", "ふ"], kun: ["あるく"] },
            { char: "武", meaning: "warrior", on: ["ぶ", "む"], kun: [] },
            { char: "歯", meaning: "tooth", on: ["し"], kun: ["は"] },
            { char: "決", meaning: "decide", on: ["けつ"], kun: ["きめる"] },
            { char: "求", meaning: "request", on: ["きゅう"], kun: ["もとめる"] },
            { char: "氷", meaning: "ice", on: ["ひょう"], kun: ["こおり"] },
            { char: "注", meaning: "pour", on: ["ちゅう"], kun: ["そそぐ"] },
            { char: "波", meaning: "wave", on: ["は"], kun: ["なみ"] },
            { char: "洋", meaning: "ocean", on: ["よう"], kun: [] },
            { char: "消", meaning: "extinguish", on: ["しょう"], kun: ["きえる"] },
            { char: "浅", meaning: "shallow", on: ["せん"], kun: ["あさい"] },
            { char: "流", meaning: "flow", on: ["りゅう", "る"], kun: ["ながれる"] },
            { char: "浴", meaning: "bathe", on: ["よく"], kun: ["あびる"] },
            { char: "深", meaning: "deep", on: ["しん"], kun: ["ふかい"] },
            { char: "混", meaning: "mix", on: ["こん"], kun: ["まざる"] },
            { char: "温", meaning: "warm", on: ["おん"], kun: ["あたたかい"] },
            { char: "港", meaning: "harbor", on: ["こう"], kun: ["みなと"] },
            { char: "湖", meaning: "lake", on: ["こ"], kun: ["みずうみ"] },
            { char: "湯", meaning: "hot water", on: ["とう"], kun: ["ゆ"] },
            { char: "遊", meaning: "play", on: ["ゆう"], kun: ["あそぶ"] },
            { char: "満", meaning: "full", on: ["まん"], kun: ["みちる"] },
            { char: "漢", meaning: "China", on: ["かん"], kun: [] },
            { char: "漁", meaning: "fishing", on: ["ぎょ"], kun: ["りょう"] },
            { char: "灯", meaning: "lamp", on: ["とう"], kun: ["ひ"] },
            { char: "無", meaning: "nothing", on: ["む"], kun: ["ない"] },
            { char: "焼", meaning: "burn", on: ["しょう"], kun: ["やく"] },
            { char: "照", meaning: "illuminate", on: ["しょう"], kun: ["てらす"] },
            { char: "熱", meaning: "heat", on: ["ねつ"], kun: ["あつい"] },
            { char: "愛", meaning: "love", on: ["あい"], kun: [] },
            { char: "片", meaning: "one-sided", on: ["へん"], kun: ["かた"] },
            { char: "特", meaning: "special", on: ["とく"], kun: [] },
            { char: "牛", meaning: "cow", on: ["ぎゅう"], kun: ["うし"] },
            { char: "牧", meaning: "pasture", on: ["ぼく"], kun: ["まき"] },
            { char: "物", meaning: "thing", on: ["ぶつ"], kun: ["もの"] },
            { char: "祭", meaning: "festival", on: ["さい"], kun: ["まつる"] },
            { char: "現", meaning: "present", on: ["げん"], kun: ["あらわれる"] },
            { char: "球", meaning: "ball", on: ["きゅう"], kun: ["たま"] },
            { char: "理", meaning: "reason", on: ["り"], kun: [] },
            { char: "産", meaning: "give birth", on: ["さん"], kun: ["うむ"] },
            { char: "田", meaning: "rice field", on: ["でん"] , kun: ["た"] },
            { char: "由", meaning: "reason", on: ["ゆう", "ゆ"], kun: ["よし"] },
            { char: "皮", meaning: "skin", on: ["ひ"], kun: ["かわ"] },
            { char: "皿", meaning: "plate", on: ["べい"], kun: ["さら"] },
            { char: "相", meaning: "inter", on: ["そう", "しょう"], kun: ["あい"] },
            { char: "県", meaning: "prefecture", on: ["けん"], kun: [] },
            { char: "真", meaning: "true", on: ["しん"], kun: ["ま"] },
            { char: "眼", meaning: "eyeball", on: ["がん"], kun: ["まなこ"] },
            { char: "着", meaning: "wear", on: ["ちゃく", "じゃく"], kun: ["きる"] },
            { char: "知", meaning: "know", on: ["ち"], kun: ["しる"] },
            { char: "移", meaning: "shift", on: ["い"], kun: ["うつる"] },
            { char: "税", meaning: "tax", on: ["ぜい"], kun: [] },
            { char: "積", meaning: "volume", on: ["せき"], kun: ["つむ"] },
            { char: "競", meaning: "compete", on: ["きょう"], kun: ["きそう"] },
            { char: "臣", meaning: "retainer", on: ["しん"], kun: ["とみ"] },
            { char: "種", meaning: "species", on: ["しゅ"], kun: ["たね"] },
            { char: "科", meaning: "section", on: ["か"], kun: [] },
            { char: "究", meaning: "research", on: ["きゅう"], kun: ["きわめる"] },
            { char: "章", meaning: "chapter", on: ["しょう"], kun: [] },
            { char: "童", meaning: "juvenile", on: ["どう"], kun: ["わらべ"] },
            { char: "竹", meaning: "bamboo", on: ["ちく"] , kun: ["たけ"] },
            { char: "筆", meaning: "writing brush", on: ["ひつ"], kun: ["ふで"] },
            { char: "答", meaning: "answer", on: ["とう"], kun: ["こたえる"] },
            { char: "策", meaning: "scheme", on: ["さく"], kun: [] },
            { char: "第", meaning: "on the whole", on: ["だい"], kun: [] },
            { char: "等", meaning: "etc.", on: ["とう"], kun: ["ひとしい"] },
            { char: "決", meaning: "decide", on: ["けつ"], kun: ["きめる"] },
            { char: "約", meaning: "promise", on: ["やく"], kun: [] },
            { char: "級", meaning: "grade", on: ["きゅう"], kun: [] },
            { char: "終", meaning: "end", on: ["しゅう"], kun: ["おわる"] },
            { char: "紀", meaning: "chronicle", on: ["き"], kun: [] },
            { char: "結", meaning: "tie", on: ["けつ"], kun: ["むすぶ"] },
            { char: "給", meaning: "salary", on: ["きゅう"], kun: ["たまう"] },
            { char: "統", meaning: "overall", on: ["とう"], kun: [] },
            { char: "絶", meaning: "discontinue", on: ["ぜつ"], kun: ["たえる"] },
            { char: "続", meaning: "continue", on: ["ぞく"], kun: ["つづく"] },
            { char: "練", meaning: "practice", on: ["れん"], kun: ["ねる"] },
            { char: "総", meaning: "general", on: ["そう"], kun: ["すべて"] },
            { char: "輸", meaning: "transport", on: ["ゆ"], kun: [] },
            { char: "編", meaning: "compile", on: ["へん"], kun: ["あむ"] },
            { char: "績", meaning: "merit", on: ["せき"], kun: [] },
            { char: "織", meaning: "weave", on: ["しょく", "しき"], kun: ["おる"] },
            { char: "罪", meaning: "guilt", on: ["ざい"], kun: ["つみ"] },
            { char: "美", meaning: "beauty", on: ["び"], kun: ["うつくしい"] },
            { char: "義", meaning: "righteousness", on: ["ぎ"], kun: [] },
            { char: "習", meaning: "learn", on: ["しゅう"], kun: ["ならう"] },
            { char: "老", meaning: "old man", on: ["ろう"], kun: ["おいる"] },
            { char: "考", meaning: "consider", on: ["こう"], kun: ["かんがえる"] },
            { char: "者", meaning: "person", on: ["しゃ"], kun: ["もの"] },
            { char: "聞", meaning: "hear", on: ["ぶん"], kun: ["きく"] },
            { char: "聖", meaning: "holy", on: ["せい"], kun: [] },
            { char: "職", meaning: "post", on: ["しょく"], kun: [] },
            { char: "肥", meaning: "fertilizer", on: ["ひ"], kun: ["こえる"] },
            { char: "能", meaning: "ability", on: ["のう"], kun: [] },
            { char: "脳", meaning: "brain", on: ["のう"], kun: [] },
            { char: "腹", meaning: "abdomen", on: ["ふく"], kun: ["はら"] },
            { char: "臓", meaning: "entrails", on: ["ぞう"], kun: [] },
            { char: "臣", meaning: "retainer", on: ["しん"], kun: ["とみ"] },
            { char: "良", meaning: "good", on: ["りょう"], kun: ["よい"] },
            { char: "舟", meaning: "boat", on: ["しゅう"], kun: ["ふね"] },
            { char: "英", meaning: "England", on: ["えい"], kun: [] },
            { char: "船", meaning: "ship", on: ["せん"], kun: ["ふね"] },
            { char: "芸", meaning: "art", on: ["げい"], kun: [] },
            { char: "芽", meaning: "bud", on: ["が"], kun: ["め"] },
            { char: "苦", meaning: "suffering", on: ["く"], kun: ["くるしい", "にがい"] },
            { char: "苗", meaning: "seedling", on: ["びょう"], kun: ["なえ"] },
            { char: "茶", meaning: "tea", on: ["ちゃ"], kun: [] },
            { char: "荷", meaning: "baggage", on: ["か"], kun: ["に"] },
            { char: "落", meaning: "fall", on: ["らく"], kun: ["おちる"] },
            { char: "葉", meaning: "leaf", on: ["よう"], kun: ["は"] },
            { char: "虫", meaning: "insect", on: ["ちゅう"], kun: ["むし"] },
            { char: "血", meaning: "blood", on: ["けつ"], kun: ["ち"] },
            { char: "行", meaning: "go", on: ["こう", "ぎょう"], kun: ["いく"] },
            { char: "術", meaning: "art", on: ["じゅつ"], kun: [] },
            { char: "街", meaning: "street", on: ["がい"], kun: ["まち"] },
            { char: "衣", meaning: "clothing", on: ["い"], kun: ["ころも"] },
            { char: "装", meaning: "attire", on: ["そう"], kun: ["よそおう"] },
            { char: "裏", meaning: "back", on: ["り"], kun: ["うら"] },
            { char: "里", meaning: "league", on: ["り"], kun: ["さと"] },
            { char: "角", meaning: "angle", on: ["かく"], kun: ["かど"] },
            { char: "計", meaning: "plan", on: ["けい"], kun: ["はかる"] },
            { char: "訓", meaning: "instruction", on: ["くん"], kun: ["おしえる"] },
            { char: "説", meaning: "explain", on: ["せつ", "ぜい"], kun: ["とく"] },
            { char: "談", meaning: "discuss", on: ["だん"], kun: [] },
            { char: "証", meaning: "proof", on: ["しょう"], kun: [] },
            { char: "象", meaning: "elephant", on: ["ぞう"], kun: [] },
            { char: "貨", meaning: "freight", on: ["か"], kun: [] },
            { char: "貯", meaning: "savings", on: ["ちょ"], kun: [] },
            { char: "費", meaning: "expense", on: ["ひ"], kun: ["ついやす"] },
            { char: "貿", meaning: "trade", on: ["ぼう"], kun: [] },
            { char: "賀", meaning: "congratulations", on: ["が"], kun: [] },
            { char: "賃", meaning: "fare", on: ["ちん"], kun: [] },
            { char: "質", meaning: "quality", on: ["しつ", "ち"], kun: [] },
            { char: "車", meaning: "car", on: ["しゃ"], kun: ["くるま"] },
            { char: "輪", meaning: "wheel", on: ["りん"], kun: ["わ"] },
            { char: "辞", meaning: "resign", on: ["じ"], kun: ["やめる"] },
            { char: "路", meaning: "path", on: ["ろ"], kun: ["じ"] },
            { char: "農", meaning: "agriculture", on: ["のう"], kun: [] },
            { char: "達", meaning: "accomplished", on: ["たつ"], kun: [] },
            { char: "遠", meaning: "distant", on: ["えん"], kun: ["とおい"] },
            { char: "遊", meaning: "play", on: ["ゆう"], kun: ["あそぶ"] },
            { char: "郵", meaning: "mail", on: ["ゆう"], kun: [] },
            { char: "閉", meaning: "closed", on: ["へい"], kun: ["とじる"] },
            { char: "開", meaning: "open", on: ["かい"], kun: ["ひらく"] },
            { char: "関", meaning: "barrier", on: ["かん"], kun: ["せき"] },
            { char: "隊", meaning: "troop", on: ["たい"], kun: [] },
            { char: "階", meaning: "story", on: ["かい"], kun: ["きざはし"] },
            { char: "陽", meaning: "positive", on: ["よう"], kun: ["ひ"] },
            { char: "際", meaning: "occasion", on: ["さい"], kun: ["ぎわ"] },
            { char: "雑", meaning: "misc.", on: ["ざつ", "ぞう"], kun: [] },
            { char: "非", meaning: "un-", on: ["ひ"], kun: ["あら"] },
            { char: "預", meaning: "deposit", on: ["よ"], kun: ["あずける"] },
            { char: "顔", meaning: "face", on: ["がん"], kun: ["かお"] },
            { char: "願", meaning: "request", on: ["がん"], kun: ["ねがう"] },
            { char: "類", meaning: "sort", on: ["るい"], kun: ["たぐい"] },
            { char: "風", meaning: "wind", on: ["ふう"], kun: ["かぜ"] },
            { char: "飯", meaning: "meal", on: ["はん"], kun: ["めし"] },
            { char: "飲", meaning: "drink", on: ["いん"], kun: ["のむ"] }
        ]
    },

    // Grade 4 (202 kanji)
    {
        grade: 4,
        kanji: [
            { char: "愛", meaning: "love", on: ["あい"], kun: [] },
            { char: "案", meaning: "plan", on: ["あん"], kun: [] },
            { char: "以", meaning: "by means of", on: ["い"], kun: [] },
            { char: "衣", meaning: "clothing", on: ["い"], kun: ["ころも"] },
            { char: "位", meaning: "rank", on: ["い"], kun: ["くらい"] },
            { char: "囲", meaning: "surround", on: ["い"], kun: ["かこむ"] },
            { char: "胃", meaning: "stomach", on: ["い"], kun: [] },
            { char: "印", meaning: "stamp", on: ["いん"], kun: ["しるし"] },
            { char: "英", meaning: "England", on: ["えい"], kun: [] },
            { char: "栄", meaning: "flourish", on: ["えい"], kun: ["さかえる"] },
            { char: "塩", meaning: "salt", on: ["えん"], kun: ["しお"] },
            { char: "億", meaning: "hundred million", on: ["おく"], kun: [] },
            { char: "加", meaning: "add", on: ["か"], kun: ["くわえる"] },
            { char: "果", meaning: "fruit", on: ["か"], kun: ["はたす"] },
            { char: "課", meaning: "chapter", on: ["か"], kun: [] },
            { char: "可", meaning: "possible", on: ["か"], kun: [] },
            { char: "仮", meaning: "sham", on: ["か", "け"], kun: ["かり"] },
            { char: "貨", meaning: "freight", on: ["か"], kun: [] },
            { char: "芽", meaning: "bud", on: ["が"], kun: ["め"] },
            { char: "改", meaning: "reformation", on: ["かい"], kun: ["あらためる"] },
            { char: "械", meaning: "contraption", on: ["かい"], kun: [] },
            { char: "害", meaning: "harm", on: ["がい"], kun: [] },
            { char: "街", meaning: "avenue", on: ["がい"], kun: ["まち"] },
            { char: "各", meaning: "each", on: ["かく"], kun: [] },
            { char: "覚", meaning: "memorize", on: ["かく"], kun: ["おぼえる"] },
            { char: "完", meaning: "perfect", on: ["かん"], kun: [] },
            { char: "官", meaning: "bureaucrat", on: ["かん"], kun: [] },
            { char: "管", meaning: "pipe", on: ["かん"], kun: ["くだ"] },
            { char: "関", meaning: "barrier", on: ["かん"], kun: ["せき"] },
            { char: "観", meaning: "outlook", on: ["かん"], kun: [] },
            { char: "願", meaning: "request", on: ["がん"], kun: ["ねがう"] },
            { char: "希", meaning: "hope", on: ["き"], kun: [] },
            { char: "季", meaning: "seasons", on: ["き"], kun: [] },
            { char: "旗", meaning: "flag", on: ["き"], kun: ["はた"] },
            { char: "器", meaning: "utensil", on: ["き"], kun: ["うつわ"] },
            { char: "機", meaning: "machine", on: ["き"], kun: ["はた"] },
            { char: "議", meaning: "deliberation", on: ["ぎ"], kun: [] },
            { char: "求", meaning: "request", on: ["きゅう"], kun: ["もとめる"] },
            { char: "泣", meaning: "cry", on: ["きゅう"], kun: ["なく"] },
            { char: "救", meaning: "save", on: ["きゅう"], kun: ["すくう"] },
            { char: "給", meaning: "salary", on: ["きゅう"], kun: ["たまう"] },
            { char: "挙", meaning: "raise", on: ["きょ"], kun: ["あげる"] },
            { char: "漁", meaning: "fishing", on: ["ぎょ"], kun: ["いさり", "りょう"] },
            { char: "共", meaning: "together", on: ["きょう"], kun: ["とも"] },
            { char: "協", meaning: "cooperation", on: ["きょう"], kun: [] },
            { char: "境", meaning: "boundary", on: ["きょう"], kun: ["さかい"] },
            { char: "競", meaning: "compete", on: ["きょう"], kun: ["きそう"] },
            { char: "極", meaning: "poles", on: ["きょく"], kun: ["きわめる"] },
            { char: "訓", meaning: "instruction", on: ["くん"], kun: ["おしえる"] },
            { char: "軍", meaning: "army", on: ["ぐん"], kun: [] },
            { char: "郡", meaning: "county", on: ["ぐん"], kun: [] },
            { char: "型", meaning: "mold", on: ["けい"], kun: ["かた"] },
            { char: "景", meaning: "scenery", on: ["けい"], kun: [] },
            { char: "芸", meaning: "art", on: ["げい"], kun: [] },
            { char: "欠", meaning: "lack", on: ["けつ"], kun: ["かける"] },
            { char: "穴", meaning: "hole", on: ["けつ"], kun: ["あな"] },
            { char: "件", meaning: "affair", on: ["けん"], kun: [] },
            { char: "権", meaning: "authority", on: ["けん"], kun: [] },
            { char: "憲", meaning: "constitution", on: ["けん"], kun: [] },
            { char: "源", meaning: "source", on: ["げん"], kun: ["みなもと"] },
            { char: "現", meaning: "present", on: ["げん"], kun: ["あらわれる"] },
            { char: "減", meaning: "decrease", on: ["げん"], kun: ["へる"] },
            { char: "故", meaning: "circumstance", on: ["こ"], kun: ["ゆえ"] },
            { char: "個", meaning: "individual", on: ["こ"], kun: [] },
            { char: "庫", meaning: "warehouse", on: ["こ"], kun: ["くら"] },
            { char: "護", meaning: "safeguard", on: ["ご"], kun: [] },
            { char: "効", meaning: "effect", on: ["こう"], kun: ["きく"] },
            { char: "厚", meaning: "thick", on: ["こう"], kun: ["あつい"] },
            { char: "耕", meaning: "till", on: ["こう"], kun: ["たがやす"] },
            { char: "鉱", meaning: "mine", on: ["こう"], kun: ["あらがね"] },
            { char: "構", meaning: "establish", on: ["こう"], kun: ["かまえる"] },
            { char: "興", meaning: "entertain", on: ["こう"], kun: ["おこる", "おこす"] },
            { char: "講", meaning: "lecture", on: ["こう"], kun: [] },
            { char: "混", meaning: "mix", on: ["こん"], kun: ["まざる"] },
            { char: "査", meaning: "investigate", on: ["さ"], kun: [] },
            { char: "際", meaning: "occasion", on: ["さい"], kun: ["ぎわ"] },
            { char: "細", meaning: "dainty", on: ["さい"], kun: ["こまかい", "ほそい"] },
            { char: "察", meaning: "guess", on: ["さつ"], kun: [] },
            { char: "雑", meaning: "misc.", on: ["ざつ", "ぞう"], kun: [] },
            { char: "算", meaning: "calculate", on: ["さん"], kun: [] },
            { char: "残", meaning: "remainder", on: ["ざん"], kun: ["のこる"] },
            { char: "司", meaning: "official", on: ["し"], kun: ["つかさどる"] },
            { char: "姿", meaning: "figure", on: ["し"], kun: ["すがた"] },
            { char: "師", meaning: "teacher", on: ["し"], kun: [] },
            { char: "志", meaning: "intention", on: ["し"], kun: ["こころざす"] },
            { char: "支", meaning: "branch", on: ["し"], kun: ["ささえる"] },
            { char: "枝", meaning: "bough", on: ["し"], kun: ["えだ"] },
            { char: "資", meaning: "assets", on: ["し"], kun: [] },
            { char: "飼", meaning: "raise", on: ["し"], kun: ["かう"] },
            { char: "示", meaning: "show", on: ["じ"], kun: ["しめす"] },
            { char: "辞", meaning: "resign", on: ["じ"], kun: ["やめる"] },
            { char: "識", meaning: "discriminating", on: ["しき"], kun: [] },
            { char: "質", meaning: "substance", on: ["しつ", "ち"], kun: [] },
            { char: "舎", meaning: "cottage", on: ["しゃ"], kun: ["やどる"] },
            { char: "謝", meaning: "apologize", on: ["しゃ"], kun: ["あやまる"] },
            { char: "授", meaning: "impart", on: ["じゅ"], kun: ["さずける"] },
            { char: "修", meaning: "discipline", on: ["しゅう"], kun: ["おさめる"] },
            { char: "述", meaning: "state", on: ["じゅつ"], kun: ["のべる"] },
            { char: "術", meaning: "art", on: ["じゅつ"], kun: [] },
            { char: "準", meaning: "standard", on: ["じゅん"], kun: [] },
            { char: "序", meaning: "preface", on: ["じょ"], kun: [] },
            { char: "招", meaning: "beckon", on: ["しょう"], kun: ["まねく"] },
            { char: "承", meaning: "acquiesce", on: ["しょう"], kun: ["うけたまわる"] },
            { char: "証", meaning: "proof", on: ["しょう"], kun: [] },
            { char: "条", meaning: "article", on: ["じょう"], kun: [] },
            { char: "状", meaning: "status quo", on: ["じょう"], kun: [] },
            { char: "常", meaning: "normal", on: ["じょう"], kun: ["とこ"] },
            { char: "情", meaning: "feelings", on: ["じょう"], kun: [] },
            { char: "織", meaning: "weave", on: ["しょく", "しき"], kun: ["おる"] },
            { char: "職", meaning: "post", on: ["しょく"], kun: [] },
            { char: "制", meaning: "system", on: ["せい"], kun: [] },
            { char: "勢", meaning: "force", on: ["せい"], kun: ["いきおい"] },
            { char: "性", meaning: "sex", on: ["せい", "しょう"], kun: [] },
            { char: "政", meaning: "politics", on: ["せい"], kun: ["まつりごと"] },
            { char: "精", meaning: "refined", on: ["せい"], kun: [] },
            { char: "製", meaning: "made in", on: ["せい"], kun: [] },
            { char: "税", meaning: "tax", on: ["ぜい"], kun: [] },
            { char: "責", meaning: "blame", on: ["せき"], kun: ["せめる"] },
            { char: "績", meaning: "merit", on: ["せき"], kun: [] },
            { char: "接", meaning: "contact", on: ["せつ"], kun: [] },
            { char: "設", meaning: "establishment", on: ["せつ"], kun: ["もうける"] },
            { char: "舌", meaning: "tongue", on: ["ぜつ"], kun: ["した"] },
            { char: "絶", meaning: "discontinue", on: ["ぜつ"], kun: ["たえる"] },
            { char: "銭", meaning: "coin", on: ["せん"], kun: ["ぜに"] },
            { char: "祖", meaning: "ancestor", on: ["そ"], kun: [] },
            { char: "素", meaning: "elementary", on: ["そ"], kun: [] },
            { char: "創", meaning: "originate", on: ["そう"], kun: ["つくる"] },
            { char: "送", meaning: "escort", on: ["そう"], kun: ["おくる"] },
            { char: "層", meaning: "layer", on: ["そう"], kun: [] },
            { char: "操", meaning: "maneuver", on: ["そう"], kun: ["あやつる"] },
            { char: "窓", meaning: "window", on: ["そう"], kun: ["まど"] },
            { char: "装", meaning: "attire", on: ["そう"], kun: ["よそおう"] },
            { char: "像", meaning: "statue", on: ["ぞう"], kun: [] },
            { char: "増", meaning: "increase", on: ["ぞう"], kun: ["ふえる", "ふやす"] },
            { char: "造", meaning: "create", on: ["ぞう"], kun: ["つくる"] },
            { char: "側", meaning: "side", on: ["そく"], kun: ["かわ"] },
            { char: "則", meaning: "rule", on: ["そく"], kun: ["のっとる"] },
            { char: "測", meaning: "fathom", on: ["そく"], kun: ["はかる"] },
            { char: "属", meaning: "belong", on: ["ぞく"], kun: [] },
            { char: "率", meaning: "ratio", on: ["そつ", "りつ"], kun: ["ひきいる"] },
            { char: "帯", meaning: "sash", on: ["たい"], kun: ["おび"] },
            { char: "態", meaning: "attitude", on: ["たい"], kun: [] },
            { char: "団", meaning: "group", on: ["だん"], kun: ["かたまり"] },
            { char: "談", meaning: "discuss", on: ["だん"], kun: [] },
            { char: "築", meaning: "construct", on: ["ちく"], kun: ["きずく"] },
            { char: "貯", meaning: "savings", on: ["ちょ"], kun: [] },
            { char: "丁", meaning: "street", on: ["ちょう"], kun: ["ひのと"] },
            { char: "帳", meaning: "notebook", on: ["ちょう"], kun: ["とばり"] },
            { char: "調", meaning: "tune", on: ["ちょう"], kun: ["しらべる"] },
            { char: "追", meaning: "chase", on: ["つい"], kun: ["おう"] },
            { char: "定", meaning: "determine", on: ["てい", "じょう"], kun: ["さだめる"] },
            { char: "程", meaning: "extent", on: ["てい"], kun: ["ほど"] },
            { char: "適", meaning: "suitable", on: ["てき"], kun: [] },
            { char: "敵", meaning: "enemy", on: ["てき"], kun: ["かたき"] },
            { char: "統", meaning: "overall", on: ["とう"], kun: [] },
            { char: "銅", meaning: "copper", on: ["どう"], kun: [] },
            { char: "導", meaning: "guide", on: ["どう"], kun: ["みちびく"] },
            { char: "徳", meaning: "benevolence", on: ["とく"], kun: [] },
            { char: "独", meaning: "single", on: ["どく"], kun: ["ひとり"] },
            { char: "任", meaning: "responsibility", on: ["にん"], kun: ["まかせる"] },
            { char: "燃", meaning: "burn", on: ["ねん"], kun: ["もえる"] },
            { char: "能", meaning: "ability", on: ["のう"], kun: [] },
            { char: "破", meaning: "rend", on: ["は"], kun: ["やぶる"] },
            { char: "判", meaning: "judgment", on: ["はん"], kun: [] },
            { char: "版", meaning: "print", on: ["はん"], kun: [] },
            { char: "非", meaning: "un-", on: ["ひ"], kun: ["あら"] },
            { char: "備", meaning: "equip", on: ["び"], kun: ["そなえる"] },
            { char: "俵", meaning: "bag", on: ["ひょう"], kun: ["たわら"] },
            { char: "評", meaning: "evaluate", on: ["ひょう"], kun: [] },
            { char: "貧", meaning: "poor", on: ["ひん", "ぴん"], kun: ["まずしい"] },
            { char: "布", meaning: "linen", on: ["ふ"], kun: ["ぬの"] },
            { char: "婦", meaning: "lady", on: ["ふ"], kun: [] },
            { char: "武", meaning: "warrior", on: ["ぶ", "む"], kun: [] },
            { char: "復", meaning: "restore", on: ["ふく"], kun: [] },
            { char: "複", meaning: "duplicate", on: ["ふく"], kun: [] },
            { char: "仏", meaning: "Buddha", on: ["ぶつ", "ふつ"], kun: ["ほとけ"] },
            { char: "編", meaning: "compile", on: ["へん"], kun: ["あむ"] },
            { char: "弁", meaning: "valve", on: ["べん"], kun: [] },
            { char: "保", meaning: "protect", on: ["ほ"], kun: ["たもつ"] },
            { char: "墓", meaning: "grave", on: ["ぼ"], kun: ["はか"] },
            { char: "報", meaning: "report", on: ["ほう"], kun: ["むくいる"] },
            { char: "豊", meaning: "bountiful", on: ["ほう"], kun: ["ゆたか"] },
            { char: "防", meaning: "ward off", on: ["ぼう"], kun: ["ふせぐ"] },
            { char: "貿", meaning: "trade", on: ["ぼう"], kun: [] },
            { char: "棒", meaning: "rod", on: ["ぼう"], kun: ["ぼう"] },
            { char: "卵", meaning: "egg", on: ["らん"], kun: ["たまご"] },
            { char: "裏", meaning: "back", on: ["り"], kun: ["うら"] },
            { char: "両", meaning: "both", on: ["りょう"], kun: ["てる", "ふたつ"] },
            { char: "量", meaning: "quantity", on: ["りょう"], kun: ["はかる"] },
            { char: "緑", meaning: "green", on: ["りょく", "ろく"], kun: ["みどり"] },
            { char: "類", meaning: "sort", on: ["るい"], kun: ["たぐい"] },
            { char: "令", meaning: "orders", on: ["れい"], kun: [] },
            { char: "例", meaning: "example", on: ["れい"], kun: ["たとえる"] },
            { char: "練", meaning: "polish", on: ["れん"], kun: ["ねる"] },
            { char: "老", meaning: "old man", on: ["ろう"], kun: ["おいる"] },
            { char: "労", meaning: "labor", on: ["ろう"], kun: [] },
            { char: "列", meaning: "row", on: ["れつ"], kun: [] }
        ]
    },

    // Grade 5 (193 kanji)
    {
        grade: 5,
        kanji: [
            { char: "久", meaning: "long time", on: ["kyū"], kun: ["hisa"] },
            { char: "仏", meaning: "Buddha", on: ["futsu", "butsu"], kun: ["hotoke"] },
            { char: "仮", meaning: "sham", on: ["ka", "ke"], kun: ["kari"] },
            { char: "件", meaning: "affair", on: ["ken"], kun: [] },
            { char: "任", meaning: "responsibility", on: ["nin"], kun: ["maka-seru"] },
            { char: "似", meaning: "resemble", on: ["ji"], kun: ["ni-ru"] },
            { char: "余", meaning: "surplus", on: ["yo"], kun: ["ama-ru"] },
            { char: "価", meaning: "value", on: ["ka"], kun: ["atai"] },
            { char: "保", meaning: "preserve", on: ["ho"], kun: ["tamo-tsu"] },
            { char: "修", meaning: "discipline", on: ["shū"], kun: ["osa-meru"] },
            { char: "個", meaning: "individual", on: ["ko"], kun: [] },
            { char: "停", meaning: "halt", on: ["tei"], kun: ["to-maru", "to-meru"] },
            { char: "備", meaning: "provide", on: ["bi"], kun: ["sona-eru"] },
            { char: "像", meaning: "statue", on: ["zō"], kun: [] },
            { char: "再", meaning: "again", on: ["sai", "sa"], kun: ["futata-bi"] },
            { char: "刊", meaning: "publish", on: ["kan"], kun: [] },
            { char: "判", meaning: "judge", on: ["han"], kun: ["waka-ru"] },
            { char: "制", meaning: "control", on: ["sei"], kun: [] },
            { char: "則", meaning: "rule", on: ["soku"], kun: ["notto-ru"] },
            { char: "効", meaning: "effect", on: ["kō"], kun: ["ki-ku"] },
            { char: "務", meaning: "duty", on: ["mu"], kun: ["tsuto-meru"] },
            { char: "勢", meaning: "energy", on: ["sei"], kun: ["ikio-i"] },
            { char: "厚", meaning: "thick", on: ["kō"], kun: ["atsu-i"] },
            { char: "句", meaning: "phrase", on: ["ku"], kun: [] },
            { char: "可", meaning: "possible", on: ["ka"], kun: [] },
            { char: "史", meaning: "history", on: ["shi"], kun: [] },
            { char: "告", meaning: "tell", on: ["koku"], kun: ["tsu-geru"] },
            { char: "喜", meaning: "rejoice, joy", on: ["ki"], kun: ["yoroko-bu"] },
            { char: "営", meaning: "manage", on: ["ei"], kun: ["itona-mu"] },
            { char: "因", meaning: "cause", on: ["in"], kun: ["yo-ru"] },
            { char: "団", meaning: "association", on: ["dan", "ton"], kun: [] },
            { char: "囲", meaning: "surround", on: ["i"], kun: ["kako-u"] },
            { char: "圧", meaning: "pressure", on: ["atsu"], kun: [] },
            { char: "在", meaning: "exist", on: ["zai"], kun: ["a-ru"] },
            { char: "均", meaning: "level", on: ["kin"], kun: [] },
            { char: "型", meaning: "model", on: ["kei"], kun: ["kata"] },
            { char: "基", meaning: "foundation", on: ["ki"], kun: ["moto-zuku"] },
            { char: "堂", meaning: "public chamber", on: ["dō"], kun: [] },
            { char: "報", meaning: "report", on: ["hō"], kun: ["muku-iru"] },
            { char: "境", meaning: "boundary", on: ["kyō"], kun: ["sakai"] },
            { char: "墓", meaning: "grave", on: ["bo"], kun: ["haka"] },
            { char: "増", meaning: "increase", on: ["zō"], kun: ["ma-su", "fu-eru"] },
            { char: "士", meaning: "gentleman", on: ["shi"], kun: [] },
            { char: "夢", meaning: "dream", on: ["mu"], kun: ["yume"] },
            { char: "妻", meaning: "wife", on: ["sai"], kun: ["tsuma"] },
            { char: "婦", meaning: "lady", on: ["fu"], kun: [] },
            { char: "容", meaning: "contain", on: ["yō"], kun: [] },
            { char: "寄", meaning: "approach", on: ["ki"], kun: ["yo-ru"] },
            { char: "導", meaning: "guide", on: ["dō"], kun: ["michibi-ku"] },
            { char: "居", meaning: "reside", on: ["kyo"], kun: ["i-ru"] },
            { char: "属", meaning: "belong", on: ["zoku"], kun: [] },
            { char: "布", meaning: "linen", on: ["fu"], kun: ["nuno"] },
            { char: "師", meaning: "expert", on: ["shi"], kun: [] },
            { char: "常", meaning: "normal", on: ["jō"], kun: ["tsune"] },
            { char: "幹", meaning: "tree trunk", on: ["kan"], kun: ["miki"] },
            { char: "序", meaning: "preface", on: ["jo"], kun: [] },
            { char: "弁", meaning: "valve", on: ["ben"], kun: [] },
            { char: "張", meaning: "stretch", on: ["chō"], kun: ["ha-ru"] },
            { char: "往", meaning: "journey", on: ["ō"], kun: [] },
            { char: "得", meaning: "acquire", on: ["toku"], kun: ["e-ru"] },
            { char: "復", meaning: "recovery", on: ["fuku"], kun: [] },
            { char: "志", meaning: "intention", on: ["shi"], kun: ["kokorozashi"] },
            { char: "応", meaning: "respond", on: ["ō"], kun: [] },
            { char: "快", meaning: "cheerful", on: ["kai"], kun: ["kokoroyo-i"] },
            { char: "性", meaning: "gender", on: ["sei", "shō"], kun: ["saga"] },
            { char: "情", meaning: "feelings", on: ["jō"], kun: ["nasa-ke"] },
            { char: "態", meaning: "condition", on: ["tai"], kun: [] },
            { char: "慣", meaning: "accustomed", on: ["kan"], kun: ["na-reru"] },
            { char: "技", meaning: "skill", on: ["gi"], kun: ["waza"] },
            { char: "招", meaning: "beckon", on: ["shō"], kun: ["mane-ku"] },
            { char: "授", meaning: "instruct", on: ["ju"], kun: ["sazu-keru"] },
            { char: "採", meaning: "pick", on: ["sai"], kun: ["to-ru"] },
            { char: "接", meaning: "contact", on: ["setsu"], kun: ["tsu-gu"] },
            { char: "提", meaning: "propose", on: ["tei"], kun: ["sa-geru"] },
            { char: "損", meaning: "loss", on: ["son"], kun: ["soko-neru"] },
            { char: "支", meaning: "support", on: ["shi"], kun: ["sasa-eru"] },
            { char: "政", meaning: "politics", on: ["sei"], kun: ["matsurigoto"] },
            { char: "故", meaning: "circumstances", on: ["ko"], kun: ["yue"] },
            { char: "救", meaning: "salvation", on: ["kyū"], kun: ["suku-u"] },
            { char: "断", meaning: "decline, refuse", on: ["dan"], kun: ["kotowa-ru"] },
            { char: "旧", meaning: "old times", on: ["kyū"], kun: [] },
            { char: "易", meaning: "easy", on: ["eki"], kun: ["yasa-shii"] },
            { char: "暴", meaning: "outburst", on: ["bō"], kun: ["aba-ku"] },
            { char: "条", meaning: "clause", on: ["jō"], kun: ["kudari"] },
            { char: "枝", meaning: "branch", on: ["shi"], kun: ["eda"] },
            { char: "査", meaning: "investigate", on: ["sa"], kun: [] },
            { char: "格", meaning: "status", on: ["kaku"], kun: [] },
            { char: "桜", meaning: "cherry", on: ["ō"], kun: ["sakura"] },
            { char: "検", meaning: "examine", on: ["ken"], kun: [] },
            { char: "構", meaning: "construct", on: ["kō"], kun: ["kama-eru"] },
            { char: "武", meaning: "military", on: ["bu", "mu"], kun: [] },
            { char: "歴", meaning: "curriculum", on: ["reki"], kun: [] },
            { char: "殺", meaning: "kill", on: ["satsu"], kun: ["koro-su"] },
            { char: "毒", meaning: "poison", on: ["doku"], kun: [] },
            { char: "比", meaning: "compare", on: ["hi"], kun: ["kura-beru"] },
            { char: "永", meaning: "eternity", on: ["ei"], kun: ["naga-i"] },
            { char: "河", meaning: "stream", on: ["ka"], kun: ["kawa"] },
            { char: "液", meaning: "fluid", on: ["eki"], kun: [] },
            { char: "混", meaning: "mix", on: ["kon"], kun: ["ma-zeru"] },
            { char: "減", meaning: "decrease", on: ["gen"], kun: ["he-ru"] },
            { char: "測", meaning: "measure", on: ["soku"], kun: ["haka-ru"] },
            { char: "準", meaning: "standard", on: ["jun"], kun: [] },
            { char: "演", meaning: "perform", on: ["en"], kun: [] },
            { char: "潔", meaning: "undefiled", on: ["ketsu"], kun: ["isagiyo-i"] },
            { char: "災", meaning: "disaster", on: ["sai"], kun: ["wazawa-i"] },
            { char: "燃", meaning: "burn", on: ["nen"], kun: ["mo-eru"] },
            { char: "版", meaning: "printing block", on: ["han"], kun: [] },
            { char: "犯", meaning: "crime", on: ["han"], kun: ["oka-su"] },
            { char: "状", meaning: "form", on: ["jō"], kun: [] },
            { char: "独", meaning: "alone", on: ["doku"], kun: ["hito-ri"] },
            { char: "率", meaning: "rate", on: ["ritsu", "sotsu"], kun: ["hiki-iru"] },
            { char: "現", meaning: "appear", on: ["gen"], kun: ["arawa-reru"] },
            { char: "留", meaning: "detain", on: ["ryū", "ru"], kun: ["todo-maru"] },
            { char: "略", meaning: "abbreviation", on: ["ryaku"], kun: [] },
            { char: "益", meaning: "benefit", on: ["eki"], kun: [] },
            { char: "眼", meaning: "eyeball", on: ["gan"], kun: ["me"] },
            { char: "破", meaning: "rend", on: ["ha"], kun: ["yabu-ru"] },
            { char: "確", meaning: "certain", on: ["kaku"], kun: ["tashi-ka"] },
            { char: "示", meaning: "indicate", on: ["shi"], kun: ["shime-su"] },
            { char: "祖", meaning: "ancestor", on: ["so"], kun: [] },
            { char: "禁", meaning: "prohibition", on: ["kin"], kun: [] },
            { char: "移", meaning: "shift", on: ["i"], kun: ["utsu-ru"] },
            { char: "程", meaning: "extent", on: ["tei"], kun: ["hodo"] },
            { char: "税", meaning: "tax", on: ["zei"], kun: [] },
            { char: "築", meaning: "fabricate", on: ["chiku"], kun: ["kizu-ku"] },
            { char: "粉", meaning: "flour", on: ["fun"], kun: ["ko", "kona"] },
            { char: "精", meaning: "refined", on: ["sei"], kun: [] },
            { char: "紀", meaning: "chronicle", on: ["ki"], kun: [] },
            { char: "素", meaning: "elementary", on: ["su", "so"], kun: ["moto"] },
            { char: "経", meaning: "manage", on: ["kei", "kyō"], kun: ["he-ru"] },
            { char: "統", meaning: "relationship", on: ["tō"], kun: ["su-beru"] },
            { char: "絶", meaning: "discontinue", on: ["zetsu"], kun: ["ta-tsu"] },
            { char: "綿", meaning: "cotton", on: ["men"], kun: ["wata"] },
            { char: "総", meaning: "whole", on: ["sō"], kun: [] },
            { char: "編", meaning: "compile", on: ["hen"], kun: ["a-mu"] },
            { char: "績", meaning: "exploits", on: ["seki"], kun: [] },
            { char: "織", meaning: "weave", on: ["shiki"], kun: ["o-ru"] },
            { char: "罪", meaning: "guilt", on: ["zai"], kun: ["tsumi"] },
            { char: "義", meaning: "righteousness", on: ["gi"], kun: [] },
            { char: "耕", meaning: "till", on: ["kō"], kun: ["tagaya-su"] },
            { char: "職", meaning: "employment", on: ["shoku"], kun: [] },
            { char: "肥", meaning: "fertilizer", on: ["hi"], kun: ["ko-yasu"] },
            { char: "能", meaning: "ability", on: ["nō"], kun: [] },
            { char: "脈", meaning: "vein", on: ["myaku"], kun: [] },
            { char: "興", meaning: "entertain", on: ["kyō"], kun: ["oko-su"] },
            { char: "舎", meaning: "cottage", on: ["sha"], kun: [] },
            { char: "航", meaning: "cruise", on: ["kō"], kun: [] },
            { char: "術", meaning: "art", on: ["jutsu"], kun: ["sube"] },
            { char: "衛", meaning: "defense", on: ["ei"], kun: [] },
            { char: "製", meaning: "manufacture", on: ["sei"], kun: [] },
            { char: "複", meaning: "duplicate", on: ["fuku"], kun: [] },
            { char: "規", meaning: "rule", on: ["ki"], kun: [] },
            { char: "解", meaning: "untie", on: ["ge", "kai"], kun: ["to-ku"] },
            { char: "設", meaning: "establish", on: ["setsu"], kun: ["mō-keru"] },
            { char: "許", meaning: "permit", on: ["kyo"], kun: ["yuru-su"] },
            { char: "証", meaning: "evidence", on: ["shō"], kun: ["akashi"] },
            { char: "評", meaning: "evaluate", on: ["hyō"], kun: [] },
            { char: "講", meaning: "lecture", on: ["kō"], kun: [] },
            { char: "謝", meaning: "apologize", on: ["sha"], kun: ["ayama-ru"] },
            { char: "識", meaning: "discriminating", on: ["shiki"], kun: [] },
            { char: "護", meaning: "safeguard", on: ["go"], kun: ["mamo-ru"] },
            { char: "豊", meaning: "bountiful", on: ["hō"], kun: ["yuta-ka"] },
            { char: "象", meaning: "elephant, figure", on: ["zō", "shō"], kun: [] },
            { char: "財", meaning: "wealth", on: ["zai"], kun: [] },
            { char: "貧", meaning: "poor", on: ["hin"], kun: ["mazu-shii"] },
            { char: "責", meaning: "blame", on: ["seki"], kun: ["se-meru"] },
            { char: "貯", meaning: "savings", on: ["cho"], kun: ["ta-meru"] },
            { char: "貸", meaning: "lend", on: ["tai"], kun: ["ka-su"] },
            { char: "費", meaning: "expense", on: ["hi"], kun: ["tsui-yasu"] },
            { char: "貿", meaning: "trade", on: ["bō"], kun: [] },
            { char: "資", meaning: "resources", on: ["shi"], kun: [] },
            { char: "賛", meaning: "approve", on: ["san"], kun: [] },
            { char: "賞", meaning: "prize", on: ["shō"], kun: [] },
            { char: "質", meaning: "quality", on: ["shitsu"], kun: [] },
            { char: "輸", meaning: "transport", on: ["yu"], kun: [] },
            { char: "述", meaning: "state, express", on: ["jutsu"], kun: ["no-beru"] },
            { char: "迷", meaning: "astray", on: ["mei"], kun: ["mayo-u"] },
            { char: "逆", meaning: "inverted", on: ["gyaku"], kun: ["saka-rau"] },
            { char: "造", meaning: "create", on: ["zō"], kun: ["tsuku-ru"] },
            { char: "過", meaning: "pass, exceed", on: ["ka"], kun: ["sugi-ru"] },
            { char: "適", meaning: "suitable", on: ["teki"], kun: [] },
            { char: "酸", meaning: "acid", on: ["san"], kun: [] },
            { char: "鉱", meaning: "mineral", on: ["kō"], kun: [] },
            { char: "銅", meaning: "copper", on: ["dō"], kun: [] },
            { char: "防", meaning: "prevent", on: ["bō"], kun: ["fuse-gu"] },
            { char: "限", meaning: "limit", on: ["gen"], kun: ["kagi-ru"] },
            { char: "険", meaning: "precipitous", on: ["ken"], kun: ["kewa-shii"] },
            { char: "際", meaning: "occasion", on: ["sai"], kun: ["kiwa"] },
            { char: "雑", meaning: "miscellaneous", on: ["zatsu"], kun: [] },
            { char: "非", meaning: "negative", on: ["hi"], kun: ["ara-zu"] },
            { char: "領", meaning: "territory", on: ["ryō"], kun: [] },
            { char: "額", meaning: "amount", on: ["gaku"], kun: ["hitai"] },
            { char: "飼", meaning: "domesticate", on: ["shi"], kun: ["ka-u"] }
        ]
    },

    // Grade 6 (191 kanji)
    {
        grade: 6,
        kanji: [
            { char: "並", meaning: "row", on: ["hei"], kun: ["nami", "nara-bu"] },
            { char: "乱", meaning: "chaos", on: ["ran"], kun: ["mida-reru"] },
            { char: "乳", meaning: "milk", on: ["nyū"], kun: ["chichi"] },
            { char: "亡", meaning: "deceased", on: ["bō"], kun: ["na-kunaru"] },
            { char: "仁", meaning: "kindness", on: ["jin"], kun: [] },
            { char: "供", meaning: "offer", on: ["kyō", "ku"], kun: ["tomo"] },
            { char: "俳", meaning: "actor", on: ["hai"], kun: [] },
            { char: "俵", meaning: "straw bag", on: ["hyō"], kun: ["tawara"] },
            { char: "値", meaning: "value", on: ["chi"], kun: ["atai"] },
            { char: "傷", meaning: "wound", on: ["shō"], kun: ["kizu"] },
            { char: "優", meaning: "superior", on: ["yū"], kun: ["yasa-shii"] },
            { char: "党", meaning: "political party", on: ["tō"], kun: [] },
            { char: "冊", meaning: "counter for books", on: ["satsu"], kun: [] },
            { char: "処", meaning: "dispose", on: ["sho"], kun: [] },
            { char: "券", meaning: "ticket", on: ["ken"], kun: [] },
            { char: "刻", meaning: "engrave", on: ["koku"], kun: ["kiza-mu"] },
            { char: "割", meaning: "divide", on: ["katsu"], kun: ["wa-ru"] },
            { char: "創", meaning: "create", on: ["sō"], kun: ["tsuku-ru"] },
            { char: "劇", meaning: "drama", on: ["geki"], kun: [] },
            { char: "勤", meaning: "diligence", on: ["kin"], kun: ["tsuto-meru"] },
            { char: "危", meaning: "dangerous", on: ["ki"], kun: ["abu-nai"] },
            { char: "卵", meaning: "egg", on: ["ran"], kun: ["tamago"] },
            { char: "厳", meaning: "strict", on: ["gen"], kun: ["kibi-shii"] },
            { char: "収", meaning: "obtain", on: ["shū"], kun: ["osa-meru"] },
            { char: "后", meaning: "queen", on: ["kō", "gō"], kun: ["kisaki"] },
            { char: "否", meaning: "negate", on: ["hi"], kun: ["ina", "iya"] },
            { char: "吸", meaning: "suck", on: ["kyū"], kun: ["su-u"] },
            { char: "呼", meaning: "call", on: ["ko"], kun: ["yo-bu"] },
            { char: "善", meaning: "virtue", on: ["zen"], kun: ["yo-i"] },
            { char: "困", meaning: "quandary", on: ["kon"], kun: ["koma-ru"] },
            { char: "垂", meaning: "droop", on: ["sui"], kun: ["ta-reru"] },
            { char: "域", meaning: "range", on: ["iki"], kun: [] },
            { char: "奏", meaning: "play music", on: ["sō"], kun: ["kana-deru"] },
            { char: "奮", meaning: "stirred up", on: ["fun"], kun: ["furu-u"] },
            { char: "姿", meaning: "shape", on: ["shi"], kun: ["sugata"] },
            { char: "存", meaning: "suppose", on: ["son"], kun: [] },
            { char: "孝", meaning: "filial piety", on: ["kō"], kun: [] },
            { char: "宅", meaning: "home", on: ["taku"], kun: ["ie"] },
            { char: "宇", meaning: "eaves", on: ["u"], kun: [] },
            { char: "宗", meaning: "religion", on: ["shū"], kun: ["sō"] },
            { char: "宙", meaning: "mid-air", on: ["chū"], kun: [] },
            { char: "宝", meaning: "treasure", on: ["hō"], kun: ["takara"] },
            { char: "宣", meaning: "proclaim", on: ["sen"], kun: ["notama-u"] },
            { char: "密", meaning: "secrecy", on: ["mitsu"], kun: [] },
            { char: "寸", meaning: "measurement", on: ["sun"], kun: [] },
            { char: "専", meaning: "specialty", on: ["sen"], kun: ["moppa-ra"] },
            { char: "射", meaning: "shoot", on: ["sha"], kun: ["i-ru"] },
            { char: "将", meaning: "leader", on: ["shō"], kun: [] },
            { char: "尊", meaning: "revered", on: ["son"], kun: ["tōto-bu"] },
            { char: "就", meaning: "concerning", on: ["shū"], kun: ["tsu-ku"] },
            { char: "尺", meaning: "measure of length", on: ["shaku"], kun: [] },
            { char: "届", meaning: "deliver", on: ["kai"], kun: ["todo-ku"] },
            { char: "展", meaning: "expand", on: ["ten"], kun: [] },
            { char: "層", meaning: "stratum", on: ["sō"], kun: [] },
            { char: "己", meaning: "self", on: ["ko"], kun: ["onore"] },
            { char: "巻", meaning: "scroll", on: ["kan"], kun: ["maki"] },
            { char: "幕", meaning: "curtain", on: ["maku", "baku"], kun: [] },
            { char: "干", meaning: "dry", on: ["kan"], kun: ["ho-su"] },
            { char: "幼", meaning: "infancy", on: ["yō"], kun: ["osana-i"] },
            { char: "庁", meaning: "government office", on: ["chō"], kun: [] },
            { char: "座", meaning: "sit", on: ["za"], kun: ["suwa-ru"] },
            { char: "延", meaning: "prolong", on: ["en"], kun: ["no-basu"] },
            { char: "律", meaning: "rhythm", on: ["ritsu"], kun: [] },
            { char: "従", meaning: "obey", on: ["jū"], kun: ["shitaga-u"] },
            { char: "忘", meaning: "forget", on: ["bō"], kun: ["wasu-reru"] },
            { char: "忠", meaning: "loyalty", on: ["chū"], kun: [] },
            { char: "恩", meaning: "grace", on: ["on"], kun: [] },
            { char: "憲", meaning: "constitution", on: ["ken"], kun: [] },
            { char: "我", meaning: "ego", on: ["ga"], kun: ["ware"] },
            { char: "批", meaning: "criticism", on: ["hi"], kun: [] },
            { char: "承", meaning: "acquiesce", on: ["shō", "jō"], kun: ["uketamawa-ru"] },
            { char: "担", meaning: "shouldering", on: ["tan"], kun: ["nina-u"] },
            { char: "拝", meaning: "worship", on: ["hai"], kun: ["oga-mu"] },
            { char: "拡", meaning: "broaden", on: ["kaku"], kun: ["hiro-geru"] },
            { char: "捨", meaning: "discard", on: ["sha"], kun: ["su-teru"] },
            { char: "探", meaning: "look for, search", on: ["tan"], kun: ["saga-su"] },
            { char: "推", meaning: "infer", on: ["sui"], kun: [] },
            { char: "揮", meaning: "brandish", on: ["ki"], kun: [] },
            { char: "操", meaning: "maneuver", on: ["sō"], kun: ["ayatsu-ru"] },
            { char: "敬", meaning: "respect", on: ["kei"], kun: ["uyama-u"] },
            { char: "敵", meaning: "enemy", on: ["teki"], kun: ["kataki"] },
            { char: "映", meaning: "reflect", on: ["ei"], kun: ["utsu-ru"] },
            { char: "晩", meaning: "nightfall", on: ["ban"], kun: [] },
            { char: "暖", meaning: "warmth", on: ["dan"], kun: ["atata-kai"] },
            { char: "暮", meaning: "livelihood", on: ["bo"], kun: ["ku-rasu"] },
            { char: "朗", meaning: "melodious", on: ["rō"], kun: ["hoga-raka"] },
            { char: "机", meaning: "desk", on: ["ki"], kun: ["tsukue"] },
            { char: "枚", meaning: "sheet of...", on: ["mai"], kun: [] },
            { char: "染", meaning: "dye", on: ["sen"], kun: ["so-meru"] },
            { char: "株", meaning: "stocks", on: ["shu"], kun: ["kabu"] },
            { char: "棒", meaning: "rod", on: ["bō"], kun: [] },
            { char: "模", meaning: "imitation", on: ["mo", "bo"], kun: [] },
            { char: "権", meaning: "rights", on: ["ken"], kun: [] },
            { char: "樹", meaning: "trees", on: ["ju"], kun: ["ki"] },
            { char: "欲", meaning: "longing", on: ["yoku"], kun: ["ho-shii"] },
            { char: "段", meaning: "steps", on: ["dan"], kun: [] },
            { char: "沿", meaning: "run alongside", on: ["en"], kun: ["so-u"] },
            { char: "泉", meaning: "fountain", on: ["sen"], kun: ["izumi"] },
            { char: "洗", meaning: "wash", on: ["sen"], kun: ["ara-u"] },
            { char: "派", meaning: "sect", on: ["ha"], kun: [] },
            { char: "済", meaning: "settle", on: ["sai"], kun: ["su-mu"] },
            { char: "源", meaning: "source", on: ["gen"], kun: ["minamoto"] },
            { char: "潮", meaning: "tide", on: ["chō"], kun: ["shio"] },
            { char: "激", meaning: "violent", on: ["geki"], kun: ["hage-shii"] },
            { char: "灰", meaning: "ashes", on: ["kai"], kun: ["hai"] },
            { char: "熟", meaning: "ripen", on: ["juku"], kun: ["u-reru"] },
            { char: "片", meaning: "one-sided", on: ["hen"], kun: ["kata"] },
            { char: "班", meaning: "corps", on: ["han"], kun: [] },
            { char: "異", meaning: "uncommon", on: ["i"], kun: ["koto-naru"] },
            { char: "疑", meaning: "doubt", on: ["gi"], kun: ["utaga-u"] },
            { char: "痛", meaning: "pain", on: ["tsū"], kun: ["ita-i"] },
            { char: "皇", meaning: "emperor", on: ["kō", "ō"], kun: [] },
            { char: "盛", meaning: "prosper", on: ["sei"], kun: ["mo-ru"] },
            { char: "盟", meaning: "alliance", on: ["mei"], kun: [] },
            { char: "看", meaning: "watch over", on: ["kan"], kun: [] },
            { char: "砂", meaning: "sand", on: ["sa", "sha"], kun: ["suna"] },
            { char: "磁", meaning: "magnet", on: ["ji"], kun: [] },
            { char: "私", meaning: "me", on: ["shi"], kun: ["watakushi", "watashi"] },
            { char: "秘", meaning: "secret", on: ["hi"], kun: ["hi-meru"] },
            { char: "穀", meaning: "cereal", on: ["koku"], kun: [] },
            { char: "穴", meaning: "hole", on: ["ketsu"], kun: ["ana"] },
            { char: "窓", meaning: "window", on: ["sō"], kun: ["mado"] },
            { char: "筋", meaning: "muscle", on: ["kin"], kun: ["suji"] },
            { char: "策", meaning: "scheme", on: ["saku"], kun: [] },
            { char: "簡", meaning: "simplicity", on: ["kan"], kun: [] },
            { char: "糖", meaning: "sugar", on: ["tō"], kun: [] },
            { char: "系", meaning: "lineage", on: ["kei"], kun: [] },
            { char: "紅", meaning: "crimson", on: ["kō"], kun: ["beni", "kurenai"] },
            { char: "納", meaning: "settlement", on: ["nō"], kun: ["osa-meru"] },
            { char: "純", meaning: "genuine", on: ["jun"], kun: [] },
            { char: "絹", meaning: "silk", on: ["ken"], kun: ["kinu"] },
            { char: "縦", meaning: "vertical", on: ["jū"], kun: ["tate"] },
            { char: "縮", meaning: "shrink", on: ["shuku"], kun: ["chidi-mu"] },
            { char: "署", meaning: "government office", on: ["sho"], kun: [] },
            { char: "翌", meaning: "forthcoming", on: ["yoku"], kun: [] },
            { char: "聖", meaning: "holy", on: ["sei"], kun: [] },
            { char: "肺", meaning: "lung", on: ["hai"], kun: [] },
            { char: "胃", meaning: "stomach", on: ["i"], kun: [] },
            { char: "背", meaning: "back", on: ["hai"], kun: ["se"] },
            { char: "胸", meaning: "chest, breast", on: ["kyō"], kun: ["mune"] },
            { char: "脳", meaning: "brain", on: ["nō"], kun: [] },
            { char: "腸", meaning: "intestines", on: ["chō"], kun: ["harawata"] },
            { char: "腹", meaning: "abdomen", on: ["fuku"], kun: ["hara"] },
            { char: "臓", meaning: "entrails", on: ["zō"], kun: [] },
            { char: "臨", meaning: "lookover", on: ["rin"], kun: ["nozo-mu"] },
            { char: "至", meaning: "climax", on: ["shi"], kun: ["ita-ru"] },
            { char: "舌", meaning: "tongue", on: ["zetsu"], kun: ["shita"] },
            { char: "若", meaning: "young", on: ["jaku"], kun: ["waka-i"] },
            { char: "著", meaning: "renowned", on: ["cho"], kun: ["arawa-su", "ichijiru-shii"] },
            { char: "蒸", meaning: "foment", on: ["jō"], kun: ["mu-su"] },
            { char: "蔵", meaning: "storehouse", on: ["zō"], kun: ["kura"] },
            { char: "蚕", meaning: "silkworm", on: ["san"], kun: ["kaiko"] },
            { char: "衆", meaning: "masses", on: ["shū"], kun: [] },
            { char: "裁", meaning: "judge", on: ["sai"], kun: ["saba-ku"] },
            { char: "装", meaning: "attire", on: ["sō", "shō"], kun: ["yosoo-u"] },
            { char: "裏", meaning: "rear", on: ["ri"], kun: ["ura"] },
            { char: "補", meaning: "supplement", on: ["ho"], kun: ["ogina-u"] },
            { char: "視", meaning: "look at", on: ["shi"], kun: ["mi-ru"] },
            { char: "覧", meaning: "perusal", on: ["ran"], kun: [] },
            { char: "討", meaning: "chastise", on: ["tō"], kun: ["u-tsu"] },
            { char: "訪", meaning: "visit", on: ["hō"], kun: ["tazu-neru"] },
            { char: "訳", meaning: "translate, reason", on: ["yaku"], kun: ["wake"] },
            { char: "詞", meaning: "term", on: ["shi"], kun: ["kotoba"] },
            { char: "誌", meaning: "document", on: ["shi"], kun: [] },
            { char: "認", meaning: "recognize", on: ["nin"], kun: ["mito-meru"] },
            { char: "誕", meaning: "born", on: ["tan"], kun: [] },
            { char: "誠", meaning: "sincerity", on: ["sei"], kun: ["makoto"] },
            { char: "誤", meaning: "mistake", on: ["go"], kun: ["ayama-ru"] },
            { char: "論", meaning: "argument, discussion", on: ["ron"], kun: [] },
            { char: "諸", meaning: "various", on: ["sho"], kun: ["moro"] },
            { char: "警", meaning: "admonish", on: ["kei"], kun: ["imashi-meru"] },
            { char: "貴", meaning: "precious", on: ["ki"], kun: ["tatto-i"] },
            { char: "賃", meaning: "fare", on: ["chin"], kun: [] },
            { char: "退", meaning: "retreat", on: ["tai"], kun: ["shirizo-ku"] },
            { char: "遺", meaning: "bequeath", on: ["i"], kun: [] },
            { char: "郵", meaning: "mail", on: ["yū"], kun: [] },
            { char: "郷", meaning: "home town", on: ["kyō"], kun: ["gō"] },
            { char: "針", meaning: "needle", on: ["shin"], kun: ["hari"] },
            { char: "銭", meaning: "coin", on: ["sen"], kun: ["zeni"] },
            { char: "鋼", meaning: "steel", on: ["kō"], kun: ["hagane"] },
            { char: "閉", meaning: "closed", on: ["hei"], kun: ["shi-meru"] },
            { char: "閣", meaning: "tower", on: ["kaku"], kun: [] },
            { char: "降", meaning: "descend", on: ["kō"], kun: ["o-riru"] },
            { char: "陛", meaning: "majesty", on: ["hei"], kun: [] },
            { char: "除", meaning: "exclude", on: ["jo", "ji"], kun: ["nozo-ku"] },
            { char: "障", meaning: "hurt", on: ["shō"], kun: ["sawa-ru"] },
            { char: "難", meaning: "difficult", on: ["nan"], kun: ["muzuka-shii"] },
            { char: "革", meaning: "leather", on: ["kaku"], kun: ["kawa"] },
            { char: "頂", meaning: "top, receive", on: ["chō"], kun: ["itada-ku"] },
            { char: "預", meaning: "deposit", on: ["yo"], kun: ["azu-keru"] },
            { char: "骨", meaning: "bone", on: ["kotsu"], kun: ["hone"] }
        ]
    }
];

// Flatten into the shape expected by the game script:
// [{ kanji, meaning, onyomi, kunyomi, grade }, ...]
// Join multiple readings into a single string for display
const kanjiData = kanjiDataByGrade.flatMap(group => {
    if (!group || !Array.isArray(group.kanji)) return [];
    return group.kanji.map(entry => ({
        kanji: entry.char,
        meaning: entry.meaning || '',
        onyomi: Array.isArray(entry.on) ? entry.on.join('、') : (entry.on || ''),
        kunyomi: Array.isArray(entry.kun) ? entry.kun.join('、') : (entry.kun || ''),
        grade: group.grade
    }));
});

// Expose globally (no ESM export; index.html loads this with a normal <script>)
window.kanjiData = kanjiData;
})();
